package org.example.symlangapi.lexer;

public enum TokenType {
    LET, IF, ELSE, WHILE, FUNCTION, RETURN,
    TRUE, FALSE,
    IDENTIFIER, NUMBER, STRING,
    PLUS, MINUS, TIMES, DIVIDE,
    EQUAL, EQUAL_EQUAL, BANG_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, SEMICOLON,
    EOF
}